### ISSUE TITLE
Proposal: torrent for downloading

### ISSUE THREAD

**Issue by russelld58** [furybsd/furybsd-livecd#176] opened 2020-09-13 15:41 UTC
Please consider providing a torrent for downloading .iso 
thanks in advance!

**Comment by probonopd** [comment] 2020-09-18 21:58
https://fosstorrents.com/distributions/furybsd/

**Comment by probonopd** [comment] 2020-09-18 21:59
Duplicate of https://github.com/furybsd/furybsd-livecd/issues/78

**Closed by probonopd** 2020-09-18 21:58 UTC
